apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-resources
rules:
- apiGroups: ["*"]
  resources: ["pods", "deployments", "configmaps", "secrets"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-namespaces
rules:
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["list"]
